### ISSUE TITLE
VBCorLib and Compatibility Modes

### ISSUE THREAD

**Issue by bryceschober** [kellyethridge/VBCorLib#11]
I'm working on a build system that builds the latest version of VBCorLib and our projects that depend on it. I descended into DLL hell with a combination of (a) using unique and temporary build directories, (b) different source sandboxes, and (c) not realizing that VB6 auto-registers every DLL it builds.

So... what do think about using binary compatibility mode instead of project compatibility mode, or have I gotten myself so confused that I don't understand the trade-offs correctly?

**Comment by kellyethridge** [comment]
VB6 is indeed generous about registering DLL's on your behalf. For your current builds I would use binary compatibility. However, when I release the official version 3.0 build it certainly will not be compatible with your version. So if you choose to ignore my release build, then you should have no problems.

**Comment by bryceschober** [comment]
Thanks for the advice. I suppose that it doesn't really make sense to commit the project in binary compatibility mode to the repository... but it might be nice to have a compatibility reference dll committed when you think 3.0 interfaces are stable.
