### ISSUE TITLE
Path.GetFullPath() relative path handling

### ISSUE THREAD

**Issue by bryceschober** [kellyethridge/VBCorLib#15]
Library Version: 3788479012173c50e1502b0d8e22f86885acdbcd

**Please tell us about your environment:**

    Operating System: Windows 10

**Current behavior:**

1. Start VB6 app
2. Path.GetFullPath(".\foo.txt") uses the working directory as launched
3. Use Microsoft CommonDialog Control's `ShowOpen()` to get a user file input.
4. Path.GetFullPath(".\foo.txt") uses the directory of the file selected by the user

**Expected/desired behavior:**

What is the expected behavior?

Path.GetFullPath(".\foo.txt") uses the same working directory as the application launched with

I'm honestly not sure if this is expected behavior of windows applications or not. Or if it's an artifact of various other old stuff. In my use case, it was surprising behavior, that probably at least deserves documenting in `GetCurrentDirectory()` and `Path.GetFullPath()`. Are there other places that would be affected by this behavior?

**Comment by kellyethridge** [comment]
Even VB's App.Path follows the same behavior so I would have to say that is the expected behavior as far as how VB works.

**Comment by bryceschober** [comment]
OK, understood.
