### ISSUE TITLE
File frmSimplyVBUnitRunner.log is useless and should be removed

### ISSUE THREAD

**Issue by gh658804** [kellyethridge/VBCorLib#36]
**I'm submitting a "bug" report**

    Library Version: 3.0.0.0

**Current behavior:**
File VBCorLib-3.0.0.zip\VBCorLib-3.0.0\Source\Tests\frmSimplyVBUnitRunner.log is useless and should be removed.

**Comment by kellyethridge** [comment]
It will be removed. Thanks!
