### ISSUE TITLE
Directory.GetFiles  Invalid characters in path.

### ISSUE THREAD

**Issue by wq1282** [kellyethridge/VBCorLib#52]
Operating System: Windows 10

```
    Dim file
    For Each file In corlib.Directory.GetFiles(corlib.Environment.GetFolderPath(Desktop) & "\")
        Debug.Print Now, file
    Next
```

`---------------------------
Project1
---------------------------
Run-time error '5':

Invalid characters in path.
---------------------------
OK   
---------------------------
`

**Comment by kellyethridge** [comment]
Hello,

I'm sorry I'm not sure what you're referring to. Your code for works fine for me. What is the actual directory path that is failing?

**Comment by kellyethridge** [comment]
Closing this due to lack of response.

**Comment by wq1282** [comment]
filename have ChrW(-29731)话
when filename Like       神话.txt
HasIllegalCharacters:Error 
PathChars(i) Is < vbSpaceChar? 
< 32 ?  
-29731 < 32
Error 
but -29731 < 0 
Not 0<xxx<32
---------------------------
CorLib
---------------------------
HasIllegalCharacters:Error:2|-29731
---------------------------
OK   
---------------------------

`
Private Function HasIllegalCharacters(ByRef Path As String) As Boolean
    Dim PathChars() As Integer
    Dim i           As Long
    
    PathChars = AllocChars(Path)
    
    For i = 0 To Len(Path) - 1
        Select Case PathChars(i)
            Case vbQuoteChar, vbLessThanChar, vbGreaterThanChar, vbPipeChar, Is < vbSpaceChar
                MsgBox "HasIllegalCharacters:Error:" & i & "|" & PathChars(i)
                HasIllegalCharacters = True
                Exit For
        End Select
    Next
    
    FreeChars PathChars
End Function
`
